#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
appVersion: "1.0"
description: |
  A Helm chart for deploying Klyshko configuration files and a scheduler.
name: klyshko-config
version: 0.1.0
