#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: castor
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    - match:
        - uri:
            prefix: /castor
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amphora
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    - match:
        - uri:
            prefix: /amphora
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
