#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: io.carbynestack.engine.params.extra
data:
  {{- $pid := (.Values.playerId | toString) -}}
  {{- range $k, $v := .Values.engineParams.macKeyShares }}
  {{- if ne $k $pid }}
  {{ $k }}_mac_key_share_p: |
    {{ .p }}
  {{ $k }}_mac_key_share_2: |
    {{- $v := get . "2"}}
    {{ $v }}
  {{- end}}
  {{- end }}
