#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerator
metadata:
  name: default-crg
spec:
  generator:
    image: {{ printf "%s/%s:%s" .Values.generator.image.registry .Values.generator.image.repository .Values.generator.image.tag }}
    imagePullPolicy: {{ .Values.generator.image.pullPolicy }}
  supports:
    {{ if .Values.generator.bitGfp.enabled }}
    - type: BIT_GFP
      batchSize: {{ .Values.generator.bitGfp.batchSize }}
    {{ end }}
    {{ if .Values.generator.inputMaskGfp.enabled }}
    - type: INPUT_MASK_GFP
      batchSize: {{ .Values.generator.inputMaskGfp.batchSize }}
    {{ end }}
    {{ if .Values.generator.inverseGfp.enabled }}
    - type: INVERSE_TUPLE_GFP
      batchSize: {{ .Values.generator.inverseGfp.batchSize }}
    {{ end }}
    {{ if .Values.generator.squareGfp.enabled }}
    - type: SQUARE_TUPLE_GFP
      batchSize: {{ .Values.generator.squareGfp.batchSize }}
    {{ end }}
    {{ if .Values.generator.multiplicationGfp.enabled }}
    - type: MULTIPLICATION_TRIPLE_GFP
      batchSize: {{ .Values.generator.multiplicationGfp.batchSize }}
    {{ end }}
    {{ if .Values.generator.bitGf2n.enabled }}
    - type: BIT_GF2N
      batchSize: {{ .Values.generator.bitGf2n.batchSize }}
    {{ end }}
    {{ if .Values.generator.inputMaskGf2n.enabled }}
    - type: INPUT_MASK_GF2N
      batchSize: {{ .Values.generator.inputMaskGf2n.batchSize }}
    {{ end }}
    {{ if .Values.generator.inverseGf2n.enabled }}
    - type: INVERSE_TUPLE_GF2N
      batchSize: {{ .Values.generator.inverseGf2n.batchSize }}
    {{ end }}
    {{ if .Values.generator.squareGf2n.enabled }}
    - type: SQUARE_TUPLE_GF2N
      batchSize: {{ .Values.generator.squareGf2n.batchSize }}
    {{ end }}
    {{ if .Values.generator.multiplicationGf2n.enabled }}
    - type: MULTIPLICATION_TRIPLE_GF2N
      batchSize: {{ .Values.generator.multiplicationGf2n.batchSize }}
    {{ end }}
