#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-vcp-config
data:
  playerCount: {{ .Values.playerCount | quote }}
  playerId: {{ .Values.playerId | quote }}
