#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

image:
  repository: minio/minio
  tag: latest
  pullPolicy: "IfNotPresent"

minio:
  key:
    access: dummy-key
    secret: dummy-secret
