#
# Copyright (c) 2021-2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Configuration of Istio infrastructure (e.g. virtual services for Carbyne Stack services).
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-istio
    chart: ../charts/istio
    wait: true
    values:
    - frontendUrl: {{ requiredEnv "FRONTEND_URL" }}
    - protocol: {{ env "PROTOCOL" | default "http" | quote }}
    - authn:
        disabled: {{ env "NO_JWT_AUTHN" | default "false" }}
        jwtRules:
          issuer: {{ env "JWT_ISSUER" | default (printf "%s://%s/iam/oauth" ( env "PROTOCOL" | default "http" ) ( requiredEnv "FRONTEND_URL" )) | quote }}
          jwksUri: {{ env "JWKS_URI" | default (printf "http://%s-thymus-hydra-public.default:4444/.well-known/jwks.json" ( requiredEnv "RELEASE_NAME" )) | quote }}
    - routes:
        hosts:
          amphora: {{ requiredEnv "RELEASE_NAME" }}-amphora
          castor: {{ requiredEnv "RELEASE_NAME" }}-castor
    - authn:
        disabled: {{ env "NO_JWT_AUTHN" | default "false" }}
        jwtRules:
          issuer: {{ requiredEnv "JWT_ISSUER" }}
          jwksUri: {{ requiredEnv "JWKS_URI" }}
