#
# Copyright (c) 2021-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Configuration of Istio infrastructure (e.g. virtual services for Carbyne Stack services).
#

{{- $isMaster := eq (requiredEnv "PLAYER_ID" | int) 0 }}
{{- $fqdn := (printf "PARTNER_FQDN_%s" (requiredEnv "PLAYER_ID")) | requiredEnv }}

releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-istio
    chart: ../charts/istio
    wait: true
    values:
    - frontendUrl: {{ $fqdn }}
    - protocol: {{ env "PROTOCOL" | default "http" | quote }}
    - ingressGateway: {{ env "CS_INGRESS_GATEWAY" | default "knative-serving/knative-ingress-gateway" | quote }}
    - authn:
        disabled: {{ env "NO_JWT_AUTHN" | default "false" }}
        jwtRules:
          issuer: {{ env "JWT_ISSUER" | default (printf "%s://%s/iam/oauth" ( env "PROTOCOL" | default "http" ) ( $fqdn )) | quote }}
          jwksUri: {{ env "JWKS_URI" | default (printf "http://%s-thymus-hydra-public.default:4444/.well-known/jwks.json" ( requiredEnv "RELEASE_NAME" )) | quote }}
    - routes:
        hosts:
          amphora: {{ requiredEnv "RELEASE_NAME" }}-amphora
          castor: {{ requiredEnv "RELEASE_NAME" }}-castor
          ephemeral:
            discovery: {{ requiredEnv "RELEASE_NAME" }}-ephemeral-discovery
          etcd: {{ requiredEnv "RELEASE_NAME" }}-etcd
    - tls:
        enabled: {{ env "TLS_ENABLED" | default true }}
        secret: {{ env "TLS_SECRET_NAME" | default "" | quote }}
    - partner:
        hosts:
        {{- range $i := until (requiredEnv "PARTNER_COUNT" | int) }}
        {{- if ne $i (requiredEnv "PLAYER_ID" | int) }}
        {{- $partnerFQDN := (printf "PARTNER_FQDN_%d" $i) | requiredEnv }}
        - {{ $partnerFQDN | quote }}
        {{- end }}
        {{- end }}
        {{- if not $isMaster }}
        etcdMaster:
          host: {{ requiredEnv "ETCD_MASTER_URL" | quote }}
          ip: {{ requiredEnv "ETCD_MASTER_IP" | quote }}
        {{ end }}
