#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Configuration of Istio infrastructure (e.g. virtual services for Carbyne Stack services).
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-istio
    chart: ../charts/istio
    wait: true
    values:
    - routes:
        hosts:
          amphora: {{ requiredEnv "RELEASE_NAME" }}-amphora
          castor: {{ requiredEnv "RELEASE_NAME" }}-castor
    - tls:
        enabled: {{ env "TLS_ENABLED" | default true }}
        secret: {{ env "TLS_SECRET_NAME" | default "" | quote }}
