#
# Copyright (c) 2021-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

repositories:
  - name: bitnami
    url: "https://charts.bitnami.com/bitnami"

{{- $isMaster := eq (requiredEnv "PLAYER_ID" | int) 0 }}

#
# Deploys etcd used as coordination service between VCPs in a VC.
#
# References:
#     https://artifacthub.io/packages/helm/bitnami/etcd
#
values:
  - etcd:
      enabled: {{ $isMaster }}
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-etcd
    chart: bitnami/etcd
    version: "8.3.1"
    condition: etcd.enabled
    wait: true
    values:
      - auth:
          rbac:
            create: false
