#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

repositories:
  - name: bitnami
    url: "https://charts.bitnami.com/bitnami"

#
# Deploys a Redis key-value store with peristence using Persistent Volume Claims
#
# References:
#     https://artifacthub.io/packages/helm/bitnami/redis/
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-redis
    chart: bitnami/redis
    version: "17.14.6"
    wait: true
    values:
      - architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: {{ env "REDIS_PERSISTENCE_ENABLED" | default true }}
            size: {{ env "REDIS_PERSISTENCE_SIZE" | default "1Gi" }}
