#
# Copyright (c) 2021-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

repositories:
  - name: carbynestack-oci
    url: "ghcr.io/carbynestack"
    oci: true

{{- $isMaster := eq (requiredEnv "PLAYER_ID" | int) 0 }}
{{- $fqdn := (printf "PARTNER_FQDN_%s" (requiredEnv "PLAYER_ID")) | requiredEnv }}

#
# Deploys a Carbyne Stack Castor Offline Tuple Store service.
#
# References:
#     https://github.com/carbynestack/castor
#
releases:
- name: {{ requiredEnv "RELEASE_NAME" }}-castor
  chart: carbynestack-oci/castor
  version: "0.3.1"
  values:
  - castor:
      noSslValidation: {{ env "NO_SSL_VALIDATION" | default false }}
      image:
        registry: {{ env "CASTOR_IMAGE_REGISTRY" | default "ghcr.io" }}
        repository: {{ env "CASTOR_IMAGE_REPOSITORY" | default "carbynestack/castor-service" }}
        tag: {{ env "CASTOR_IMAGE_TAG" | default "0.2.1" }}
        {{ if env "IMAGE_PULL_SECRET" }}
        pullSecrets:
          - {{ env "IMAGE_PULL_SECRET" }}
        {{ end }}
      isMaster: {{ $isMaster | quote }}
      slaveUris:
      {{- range $i := until (requiredEnv "PARTNER_COUNT" | int) }}
      {{- if ne $i (requiredEnv "PLAYER_ID" | int) }}
      {{- $partnerFQDN := (printf "PARTNER_FQDN_%d" $i) | requiredEnv }}
      - {{ printf "http://%s/castor" $partnerFQDN | quote }}
      {{- end }}
      {{- end }}
      minio:
        endpoint: http://{{ requiredEnv "RELEASE_NAME" }}-minio:9000
      redis:
        host: {{ requiredEnv "RELEASE_NAME" }}-redis-master
      db:
        host: cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms
        userSecretName: cs.cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms.credentials.postgresql.acid.zalan.do
        passwordSecretName: cs.cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms.credentials.postgresql.acid.zalan.do
      logLevel: DEBUG
  - service:
      type: ClusterIP
      annotations:
