#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Deploys configuration for the Carbyne Stack Klyshko Offline Tuple Generation service.
#
# References:
#     https://github.com/carbynestack/klyshko
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-klyshko-config
    chart: ../charts/klyshko
    values:
      - scheduler:
          enabled: {{ env "IS_MASTER" | default "false" }}
          concurrency: {{ env "KLYSHKO_CONCURRENCY" | default 2 }}
          ttlSecondsAfterFinished: {{ env "KLYSHKO_TTL_SECONDS_AFTER_FINISHED" | default 120 }}
          # Assigning a higher priority to GFp bits, GFp input masks, and multiplication triples
          # to get us going quickly after launching the stack.
          bitGfp:
            enabled: {{ env "KLYSHKO_SCHEDULER_BIT_GFP_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_BIT_GFP_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_BIT_GFP_PRIORITY" | default 10 }}
          inputMaskGfp:
            enabled: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GFP_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GFP_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GFP_PRIORITY" | default 10 }}
          inverseGfp:
            enabled: {{ env "KLYSHKO_SCHEDULER_INVERSE_GFP_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_INVERSE_GFP_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_INVERSE_GFP_PRIORITY" | default 1 }}
          squareGfp:
            enabled: {{ env "KLYSHKO_SCHEDULER_SQUARE_GFP_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_SQUARE_GFP_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_SQUARE_GFP_PRIORITY" | default 1 }}
          multiplicationGfp:
            enabled: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GFP_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GFP_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GFP_PRIORITY" | default 10 }}
          bitGf2n:
            enabled: {{ env "KLYSHKO_SCHEDULER_BIT_GF2N_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_BIT_GF2N_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_BIT_GF2N_PRIORITY" | default 1 }}
          inputMaskGf2n:
            enabled: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GF2N_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GF2N_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_INPUT_MASK_GF2N_PRIORITY" | default 1 }}
          inverseGf2n:
            enabled: {{ env "KLYSHKO_SCHEDULER_INVERSE_GF2N_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_INVERSE_GF2N_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_INVERSE_GF2N_PRIORITY" | default 1 }}
          squareGf2n:
            enabled: {{ env "KLYSHKO_SCHEDULER_SQUARE_GF2N_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_SQUARE_GF2N_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_SQUARE_GF2N_PRIORITY" | default 1 }}
          multiplicationGf2n:
            enabled: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GF2N_ENABLED" | default "true" }}
            threshold: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GF2N_THRESHOLD" | default 100000 }}
            priority: {{ env "KLYSHKO_SCHEDULER_MULTIPLICATION_GF2N_PRIORITY" | default 1 }}
      - generator:
          image:
            registry: {{ env "KLYSHKO_IMAGE_REGISTRY" | default "ghcr.io" }}
            repository: {{ env "KLYSHKO_GENERATOR_IMAGE_REPOSITORY" | default "carbynestack/klyshko-mp-spdz" }}
            tag: {{ env "KLYSHKO_GENERATOR_IMAGE_TAG" | default "0.2.0" }}
            pullPolicy: {{ env "KLYSHKO_GENERATOR_IMAGE_PULL_POLICY" | default "IfNotPresent" }}
          bitGfp:
            enabled: {{ env "KLYSHKO_GENERATOR_BIT_GFP_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_BIT_GFP_BATCH_SIZE" }}
          inputMaskGfp:
            enabled: {{ env "KLYSHKO_GENERATOR_INPUT_MASK_GFP_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_INPUT_MASK_GFP_BATCH_SIZE" }}
          inverseGfp:
            enabled: {{ env "KLYSHKO_GENERATOR_INVERSE_GFP_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_INVERSE_GFP_BATCH_SIZE" }}
          squareGfp:
            enabled: {{ env "KLYSHKO_GENERATOR_SQUARE_GFP_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_SQUARE_GFP_BATCH_SIZE" }}
          multiplicationGfp:
            enabled: {{ env "KLYSHKO_GENERATOR_MULTIPLICATION_GFP_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_MULTIPLICATION_GFP_BATCH_SIZE" }}
          bitGf2n:
            enabled: {{ env "KLYSHKO_GENERATOR_BIT_GF2N_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_BIT_GF2N_BATCH_SIZE" }}
          inputMaskGf2n:
            enabled: {{ env "KLYSHKO_GENERATOR_INPUT_MASK_GF2N_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_INPUT_MASK_GF2N_BATCH_SIZE" }}
          inverseGf2n:
            enabled: {{ env "KLYSHKO_GENERATOR_INVERSE_GF2N_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_INVERSE_GF2N_BATCH_SIZE" }}
          squareGf2n:
            enabled: {{ env "KLYSHKO_GENERATOR_SQUARE_GF2N_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_SQUARE_GF2N_BATCH_SIZE" }}
          multiplicationGf2n:
            enabled: {{ env "KLYSHKO_GENERATOR_MULTIPLICATION_GF2N_ENABLED" | default "true" }}
            batchSize: {{ env "KLYSHKO_GENERATOR_MULTIPLICATION_GF2N_BATCH_SIZE" }}
        playerCount: 2
        playerId: {{ if eq (env "IS_MASTER") "true" }}0{{ else }}1{{ end }}
        engineParams:
          prime: {{ env "SPDZ_PRIME" | default "198766463529478683931867765928436695041" | quote }}
          macKeyShares:
            "0":
              "p": {{ env "0_MAC_KEY_SHARE_P" | default "-88222337191559387830816715872691188861" | quote }}
              "2": {{ env "0_MAC_KEY_SHARE_2" | default "f0cf6099e629fd0bda2de3f9515ab72b" | quote }}
            "1":
              "p": {{ env "1_MAC_KEY_SHARE_P" | default "1113507028231509545156335486838233835" | quote }}
              "2": {{ env "0_MAC_KEY_SHARE_2" | default "c347ce3d9e165e4e85221f9da7591d98" | quote }}
