#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Creates a postgres cluster with all required users and databases using the Zalando postgres-operator.
#
# References:
#     https://github.com/zalando/postgres-operator
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-postgres
    chart: ../charts/postgres-dbms
    wait: true
    values:
      - users:
          # superuser role
          cs:
          - superuser
          - createdb
          - login
      - databases: # name: owner
          castor: cs
          amphora: cs
