#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Creates a Minio tenant using the Minio operator.
#
# References:
#     https://github.com/minio/operator
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-minio
    chart: ../charts/minio
    wait: true
