#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

repositories:
  - name: carbynestack-oci
    url: "ghcr.io/carbynestack"
    oci: true

#
# Deploys a Carbyne Stack Castor Offline Tuple Store service.
#
# References:
#     https://github.com/carbynestack/castor
#
releases:
- name: {{ requiredEnv "RELEASE_NAME" }}-castor
  chart: carbynestack-oci/castor
  version: "0.1-SNAPSHOT-1576642733-7-72de814"
  values:
  - castor:
      noSslValidation: {{ env "NO_SSL_VALIDATION" | default false }}
      image:
        registry: {{ env "CASTOR_IMAGE_REGISTRY" | default "ghcr.io" }}
        repository: {{ env "CASTOR_IMAGE_REPOSITORY" | default "carbynestack/castor-service" }}
        tag: {{ env "CASTOR_IMAGE_TAG" | default "0.1-SNAPSHOT-1576642733-7-72de814" }}
        {{ if env "IMAGE_PULL_SECRET" }}
        pullSecrets:
          - {{ env "IMAGE_PULL_SECRET" }}
        {{ end }}
      isMaster: {{ env "IS_MASTER" | default "true" }}
      {{ if env "CASTOR_SLAVE_URI" }}
      slaveUri: {{ env "CASTOR_SLAVE_URI" }}
      {{ end }}
      minio:
        endpoint: http://{{ requiredEnv "RELEASE_NAME" }}-minio:9000
      redis:
        host: {{ requiredEnv "RELEASE_NAME" }}-redis
      db:
        host: cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms
        userSecretName: cs.cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms.credentials.postgresql.acid.zalan.do
        passwordSecretName: cs.cs-{{ requiredEnv "RELEASE_NAME" }}-postgres-dbms.credentials.postgresql.acid.zalan.do
      logLevel: DEBUG
  - service:
      type: ClusterIP
      annotations:
  - redis:
      name: {{ requiredEnv "RELEASE_NAME" }}-redis
      image:
        {{ if env REDIS_REPOSITORY }}
        repository: {{ env REDIS_REPOSITORY }}
        {{ end }}
        tag: {{ env "REDIS_IMAGE_TAG" | default "6.2.5" }}
        {{ if env IMAGE_PULL_SECRET }}
        pullSecrets:
          - {{ env "IMAGE_PULL_SECRET" }}
        {{ end }}
