#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Deploys configuration for the Carbyne Stack Klyshko Offline Tuple Generation service.
#
# References:
#     https://github.com/carbynestack/klyshko
#
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}-klyshko-config
    chart: ../charts/klyshko
    values:
      - scheduler:
          enabled: {{ env "IS_MASTER" | default "false" }}
          concurrency: {{ env "KLYSHKO_CONCURRENCY" | default 2 }}
          threshold: {{ env "KLYSHKO_THRESHOLD" | default 50000 }}
          ttlSecondsAfterFinished: {{ env "KLYSHKO_TTL_SECONDS_AFTER_FINISHED" | default 120 }}
          generator:
            image: {{ env "KLYSHKO_GENERATOR_IMAGE" | default "ghcr.io/carbynestack/klyshko-mp-spdz:0.2.0" }}
            imagePullPolicy: {{ env "KLYSHKO_GENERATOR_IMAGE_PULL_POLICY" | default "IfNotPresent" }}
        playerCount: 2
        playerId: {{ if eq (env "IS_MASTER") "true" }}0{{ else }}1{{ end }}
        engineParams:
          prime: {{ env "SPDZ_PRIME" | default "198766463529478683931867765928436695041" | quote }}
          macKeyShares:
            0:
              p: {{ env "0_MAC_KEY_SHARE_P" | default "-88222337191559387830816715872691188861" | quote }}
              2: {{ env "0_MAC_KEY_SHARE_2" | default "f0cf6099e629fd0bda2de3f9515ab72b" | quote }}
            1:
              p: {{ env "1_MAC_KEY_SHARE_P" | default "1113507028231509545156335486838233835" | quote }}
              2: {{ env "0_MAC_KEY_SHARE_2" | default "c347ce3d9e165e4e85221f9da7591d98" | quote }}
