#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-to-partner-vcp
spec:
  host: {{ .Values.partner.hosts | quote }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: MUTUAL
      credentialName: {{ .Values.tls.secret | quote }}
