#
# Copyright (c) 2024-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if not .Values.authn.disabled }}
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-authn"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - forwardOriginalToken: true
    issuer: {{ .Values.authn.jwtRules.issuer }}
    jwksUri: {{ .Values.authn.jwtRules.jwksUri }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "jwt-authn-policy"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action:  ALLOW
  rules:
    - to:
      - operation:
          # Allow general access to all requests to the etc mtls ingress gateways:
          # - 9379: inter-vcp etcd
          # AuthN and AuthZ is handled via mtls.
          ports: ["9379"]
    - from:
        # Allow everyone to access referenced endpoints
        - source:
            notRequestPrincipals: ["*"]
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            # Allow general access to all requests to the mtls ingress gateways:
            # - 9443: inter-vcp http
            # AuthN and AuthZ is handled via mtls.
            ports: ["9443"]
    - from:
        # Allow everyone to access referenced endpoints
        - source:
            notRequestPrincipals: ["*"]
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            # Allow general access on all iam related endpoints
            notPaths: ["/iam/oauth/admin*"]
            paths: ["/iam/ui*", "/iam/oauth/*", "/iam/self-service*"]
        - operation:
            # ToDo: remove inter-vcp and intra-wcp whitelist once secure-channels are implemented
            # ToDO: remove /protobuf.Discovery once secure-channels are implemented for epmhemeral discovery service
            paths: ["/protobuf.Discovery*"]
    - to:
        # Allow all MPC party interactions. AuthN and AuthZ is handled via mtls established by ephemeral and its mpc
        # framework(s).
        - operation:
            ports: ["30000", "30001", "30002", "30003", "30004"]
    - from:
        # Authenticated users only can access public ephemeral and amphora endpoints
        # Castor telemetry is also allowed for the time being for demo purposes
        - source:
            requestPrincipals: [{{ printf "%s://%s/iam/oauth/*" .Values.protocol .Values.frontendUrl | quote }}]
      to:
        - operation:
            # Allow all paths for subdomains of the frontend URL
            # This allows general access to ephemeral function containers
            hosts: [{{ printf "*.%s" .Values.frontendUrl | quote }}]
            paths: ["/"]
        - operation:
            # Allow general access on all iam related endpoints
            paths: ["/iam*"]
        - operation:
            # Amphora public endpoints
            paths: ["/amphora/input-masks", "/amphora/masked-inputs", "/amphora/secret-shares*"]
        - operation:
            # Castor telemetry endpoint
            paths: ["/castor/intra-vcp/telemetry"]
{{- end }}
