#
# Copyright (c) 2021-2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-authn"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - forwardOriginalToken: true
    issuer: {{ .Values.authn.jwtRules.issuer }}
    jwksUri: {{ .Values.authn.jwtRules.jwksUri }}
---
{{- if not .Values.authn.disabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "jwt-authn-policy"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action:  ALLOW
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
    to:
    - operation:
        # Allow general access on all iam related endpoints and intra-vcp and
        # inter-vcp endpoints
        # ToDo: remove inter-vcp and intra-wcp whitelist once tunneling is implemented
        # ToDO: remove /protobuf.Discovery once tunneling is implemented for epmhemeral discovery service
        paths: ["/iam*", "/amphora/inter-vcp*", "/amphora/intra-vcp*", "/castor/inter-vcp*", "/castor/intra-vcp*", "/protobuf.Discovery*"]
  - from:
    - source:
        notRequestPrincipals: ["*"]
    to:
    - operation:
        # Allow all paths for subdomains of the frontend URL
        # This allows general access to empeheral function containers
        # ToDo: remove this (the whole from statement) once tunneling is implemented
        hosts: [{{ printf "*.%s" .Values.frontendUrl | quote }}]
        paths: ["*"]
  - from:
    # Allow MP-SPDZ to connect to proxied server (required by 'slaves')
    # ToDo: remove this (the whole from statement) once tunneling is implemented
    - source:
        hosts: ["*-mpc-service.default.svc.cluster.local"]
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        paths: ["*"]
{{- end }}
