#
# Copyright (c) 2021-2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: castor-inter-vcp
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /castor/inter-vcp
      rewrite:
        uri: /inter-vcp
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: castor
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    - match:
        - uri:
            prefix: /castor
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amphora-inter-vcp
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /amphora/inter-vcp
      rewrite:
        uri: /inter-vcp
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amphora
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    - match:
        - uri:
            prefix: /amphora
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-inter-vcp-through-egress-gateway
spec:
  hosts:
  - {{ .Values.partner.hosts | quote }}
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: partner-vcp
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: {{ .Values.partner.hosts | quote }}
        port:
          number: 443
      weight: 100
