#
# Copyright (c) 2021-2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: castor-inter-vcp
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /castor/inter-vcp
      rewrite:
        uri: /inter-vcp
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
    - match:
        - uri:
            prefix: /castor/intra-vcp
      rewrite:
        uri: /intra-vcp
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: castor
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    - match:
        # only telemetry is exposed to the public
        - uri:
            prefix: /castor/intra-vcp/telemetry
      rewrite:
        uri: /intra-vcp/telemetry
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
    - match:
        - uri:
            prefix: /castor
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 404
      route:
        - destination:
            port:
              number: 10100
            host: {{ .Values.routes.hosts.castor }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amphora-inter-vcp
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /amphora/inter-vcp
      rewrite:
        uri: /inter-vcp
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amphora
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway
  http:
    # inter-vcp and intra-vcp are excluded from public access
    - name: "amphora-inter-vcp-route"
      match:
        - uri:
            prefix: /amphora/inter-vcp
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 404
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
    - name: "amphora-intra-vcp-route"
      match:
        - uri:
            prefix: /amphora/intra-vcp
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 404
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
    - name: "amphora-public-route"
      match:
        - uri:
            prefix: /amphora
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 10000
            host: {{ .Values.routes.hosts.amphora }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ephemeral
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /protobuf.Discovery
      route:
        - destination:
            port:
              number: 8080
            host: {{ .Values.routes.hosts.ephemeral.discovery }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: etcd
spec:
  hosts:
    - "*"
  gateways:
    - cs-service-gateway-mtls
  http:
    - match:
        - uri:
            prefix: /etcdserverpb
      route:
        - destination:
            port:
              number: 2379
            host: {{ .Values.routes.hosts.etcd }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-inter-vcp-through-egress-gateway
spec:
  hosts:
    - {{ .Values.partner.hosts | quote }}
  gateways:
    - partner-egressgateway
    - mesh
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - partner-egressgateway
          port: 80
      route:
        - destination:
            host: {{ .Values.partner.hosts | quote }}
            port:
              number: 80
          weight: 100
