apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: partner-vcp
spec:
  hosts:
  - {{ .Values.partner.hosts | quote }}
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
