#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: 'Auto Labeler'

on:

  # Allow workflow to be triggered manually
  workflow_dispatch:

  issues:
    types:
      - reopened
      - opened

jobs:
  
  # re-usable workflow @see https://docs.github.com/en/actions/using-workflows/reusing-workflows
  stale-issue-cleanup:
    uses: carbynestack/.github/.github/workflows/auto-labeler.yml@main
