#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          signoff: "cs-minion <rng_cr_carbynestack@bosch.com>"
          token: ${{ secrets.CS_MINION_PAT }}
